google/neuroglancer

src/neuroglancer/sliceview/backend_chunk_decoders/postprocess.ts

The actual size of a chunk can be smaller than the one reported in the
VolumeChunkSpecification, if the requested chunk was not fully contained
in the volume.

bugfix: chunk compression should use actual size of chunk

---

src/neuroglancer/datasource/dvid/backend.ts
src/neuroglancer/datasource/dvid/base.ts
src/neuroglancer/datasource/dvid/frontend.ts

DVID does not have a specific datatype for multi-scale chunk data.  However, a power of two pyramid is created by convention.  For example, for a data instance 'grayscale', 'grayscale_1', 'grayscale_2', etc represents multiple levels.  I made a small modification to the dvid frontend to check for this convention.
As noted by the author, DVID also does not indicate which tiles are available for its imagetile datatype (XY, YZ, and/or XZ).  However, by default, DVID returns a blank tile if nothing is available.  I changed the default to expect all orientations given that the performance is really slow anyway for XZ and YZ if only XY is assumed.
I added some basic parsing of the DVID dag so that the version history can be observed (segmentation can now be viewed at different points in time). …

improved dvid backend support

---

python/neuroglancer/__init__.py
python/setup.py

This is the current version uploaded to PyPI, 0.0.6, which is now used by nyroglancer.

small change to use neuroglancer-python in nyroglancer, version bump

---

src/neuroglancer/datasource/render/backend.ts
src/neuroglancer/datasource/render/base.ts
src/neuroglancer/datasource/render/frontend.ts
src/neuroglancer/sliceview/backend_chunk_decoders/jpeg.ts
src/neuroglancer/sliceview/decode_jpeg_stack.ts
src/neuroglancer/util/array.spec.ts
src/neuroglancer/util/array.ts

This pull request adds support for render (https://github.com/saalfeldlab/render) as a datasource. Major features are complete, including stack name auto-completion in the add dialogue, metadata parsing from render, and of course displaying render tiles. The major incomplete feature is handling multi-scale render data (i.e. render data w/ generated mipmaps). 
decode_jpeg_stack has also been modified to support 3-channel (RGB) jpegs. A test was added in decode_jpeg_stack.spec.ts.

A first pass at render support 

---

config/webpack_helpers.js
src/neuroglancer/sliceview/decode_jpeg_stack.ts

Added render datasource files to the webpack configuration. In addition, the arguments to the transpose function in decode_jpeg_stack for 3 channel jpegs were incorrect. The major axis should be width*height, and the minor axis is 3.
Sorry about that -- not sure how that bug slipped through the original pull request.

fix(render): incorrect transpose arguments when decoding jpeg stack

---

src/neuroglancer/datasource/ndstore/backend.ts
src/neuroglancer/datasource/ndstore/base.ts
src/neuroglancer/datasource/ndstore/frontend.ts
src/neuroglancer/datasource/openconnectome/frontend.ts

The openconnectome datasource continues to use /ocp/ca for compatibility with openconnecto.me. The ndstore datasource has been updated to use /nd/sd, which is compatible with all other ndstore instances currently in production use. Additionally, a neariso parameter has been added to the path, allowing the user to disable neariso for ndstore instances that do not have neariso tables generated [yet].
Adding `?neariso=false` to the end of the path will disable using the neariso tables. This isn't recommended, but is useful for newly uploaded projects (visualization while neariso tables are being generated) or for debugging. 
As an example, the following URL works in the dev server (using the old path prefix): 
```
http://localhost:8080/#!{'layers':{'image':{'type':'image'_'source':'openconnec …
```

Fix: Update ndstore datasource to use new url format

---

src/neuroglancer/datasource/render/frontend.ts

The most important fix here is proper autocompletion of projects and remediation of a bug that prevented proper handling of two stacks with the same project name. A numlevels parameter has also been added to override the number of generated mipmap levels pending better support for automatically retrieving that information from Render. Typically one would use this parameter to set the number of mipmap levels to 0 for datasets without generated mipmaps.

Render datasource fixes

---

src/neuroglancer/datasource/brainmaps/api.ts
src/neuroglancer/datasource/brainmaps/backend.ts
src/neuroglancer/datasource/brainmaps/frontend.ts

Since the new binary endpoints respect the "Accept-encoding: gzip" header, decoding in javascript via pako is no longer necessary.

Update brainmaps datasources to use new binary endpoints. 

---

src/neuroglancer/mesh/frontend.ts

Without this change, there's an error in the dependent project compile about MeshSource not being defined. Doesn't seem to affect Neuroglancer compiles.

Reorder classes to avoid compile error in dependent project

---

src/neuroglancer/datasource/brainmaps/api.ts
src/neuroglancer/util/http_request.ts

Typescript 2.3 was released <= 1 day ago and has one breaking change in that XMLHttpRequest's responseType was changed from "string" to an explicit type. 
Note: Might also want to update to enforce that ts 2.3.1 is required in package.json

(fix brainmaps): Update types for TS2.3.1

---

python/neuroglancer/downsample.py

This fixes
TypeError: 'float' object cannot be interpreted as an index

Use 'dtype=np.float32' instead of 'float' for np.zeros()

---

src/neuroglancer/layer.ts

Quick fix that makes getVisibleLayers return an array instead of an iterator. This caused problems when the return value was stored, e.g.:
```
let visibleLayers = layerManager.getVisibleLayers();
for (let layer of visibleLayers) {
console.log(layer); // <--- all layers printed
}
for (let layer of visibleLayers) {
console.log(layer); // <--- Not hit, since visibleLayers iterator is exhausted and not reset.
}
```

Fix: Return an array from getVisibleLayers instead of an iterator

---

src/neuroglancer/mesh/frontend.ts
src/neuroglancer/perspective_view/panel.ts
src/neuroglancer/single_mesh/frontend.ts
src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts

Hello.
First, thank you very much for your work. It's truly awesome and helped us really a lot.
In our project we are extending some of neuroglancer classes to implement custom functionality specific to our needs. But we need access to some members of base classes which are declared `private`. It is possible with typescript, so it does not block us, but produces unnecessary clatter in diffs and might be harder to maintain.
Is there any strong reason to keep them private? Otherwise we suggest to promote at least the ones we use to `protected` to make our work easier.
Thank you in advance
Best regards, Pavel

Increase visibility of some private members

---

src/neuroglancer/datasource/brainmaps/backend.ts
src/neuroglancer/mesh/backend.ts
src/neuroglancer/segmentation_display_state/backend.ts
src/neuroglancer/segmentation_display_state/base.ts
src/neuroglancer/segmentation_display_state/frontend.ts
src/neuroglancer/segmentation_user_layer.ts
src/neuroglancer/util/geom.ts
src/neuroglancer/util/uint64.ts

Add a shared_trackable_value class that allows two-way communication of values from frontend<->backend. Example use case is for applying (optional) ClipBounds to meshes.

Feature: ClipBounds

---

src/neuroglancer/datasource/render/backend.ts
src/neuroglancer/datasource/render/base.ts
src/neuroglancer/datasource/render/frontend.ts
src/neuroglancer/datasource/render/register_default.ts
src/neuroglancer/util/json.ts

Fix a rounding bug that occurs when setting clip bounds for projects with multiple levels.
Support channels.
Add support for the following query params:
- `minIntensity`: resample from this value to `maxIntensity`
- `maxIntensity`: resample from `minIntensity` 
- `filter`: local contrast normalization
- `maxTilesToRender`: limit the number of rendered tile specs for each bounding box

Render Datasource Improvements

---

src/neuroglancer/image_user_layer.ts
src/neuroglancer/sliceview/frontend.ts
src/neuroglancer/sliceview/renderlayer.ts
src/neuroglancer/sliceview/volume/image_renderlayer.ts
src/neuroglancer/trackable_blend.ts

This commit adds a new `blend` property to each layer, allowing the user to change the blend function used on a per-layer basis. Currently, only `additive` blending is supported, but others modes could be added in the `trackable_blend` file. Note that `additive` blending is always enabled, whereas the `default` blend mode is only enabled after the first layer has been added. This mirrors existing behavior.
It might make sense to add `none` as an option, for layers that have blending totally disabled. It would seem like the default should continue to be `gl.blendFunc(gl.SRC_ALPHA, gl.ONE_MINUS_SRC_ALPHA);` for backwards compatibility.

feat(sliceview): Support per-layer blend functions

---

python/ext/src/on_demand_object_mesh_generator.cc
python/setup.py

I had to make two tiny changes to build the C++ extension on my mac:
- Compile with `-stdlib=libc++`
- `<endian.h>` does not exist on Mac.  Mac has `<machine/endian.h>` but apparently it doesn't define `htole32()`.

Support python extension on mac

---

src/neuroglancer/uint64_set.ts

UInt64Sets were serialized and sorted according to their hashed value, not their value. This resulted in indeterminate order when serializing state.

Sort values during UInt64Set serialization.

---

src/neuroglancer/viewer.ts

This allows dependent projects to add global settings into the viewer Context Menu simply by extending the viewer class.

Increase visibility of the viewer contextMenu widget

---

python/neuroglancer/viewer_state.py

When getting layers directly in python3 programs, the existence of the `basestring` type causes an error. Replacing with six seems to resolve the problem, but a quick test of existing programs in python2 would be appreciated. My python3 tests are more exhaustive.

fix(python): Python3 compatibility for ViewerState

---

src/neuroglancer/datasource/render/frontend.ts

The render datasource gives inclusive stack bounds, and it seems that neuroglancer gives non-inclusive stack bounds.  This results in the last z section of render stacks not being rendered.  This should fix that problem.

fixed off by one error in stack bounds

---

src/neuroglancer/util/uint64.spec.ts
src/neuroglancer/util/uint64.ts

`tryParseString` fails when the `low` part overflows.

fix(util/uint64): string to uint64 conversion with low32 overflow

---

config/karma.conf.js

Something introduced in 9c8a392391452b55b99ce597a7e5b94bef5620a3 causes `npm run test` to fail, complaining about missing plugin `extract-text-webpack-plugin`. Not sure what, or why it worked before...

fix(karma): "extract-text-webpack-plugin" loader is used without the corresponding plugin

---

src/neuroglancer/datasource/render/frontend.ts

Add minX,minY,minZ,maxX,maxY and maxZ flags to the render datasource to override the returned bounding box. This is necessary to support stacks in the LOADING state, on which no precalculated bbox is available.
Additionally, stacks in READ_ONLY state are viewable as well.
Feature requested by @fcollman [#73]

feature(datasource/render): add {min,max}{X,Y,Z} query parameters to override render bbox

---

src/neuroglancer/datasource/dvid/backend.ts
src/neuroglancer/datasource/dvid/base.ts
src/neuroglancer/datasource/dvid/frontend.ts

All changes were made within the dvid datasource.
* Adds supported for faster, pre-computed JPEG grayscale blocks
* Adds support for new multi-scale segmentation datatype
* Adds support for showing skeletons stored in DVID
* Fixes a bug in the offset calculation
* Removes support for dvid image tiles since its use in DVID is mostly deprecated and a non-ideal fit for neuroglancer
tslint and clang-format were run on the files.

updates to DVID driver

---

src/neuroglancer/datasource/dvid/backend.ts
src/neuroglancer/datasource/dvid/base.ts
src/neuroglancer/datasource/dvid/frontend.ts

This commit adds support for meshes with the DVID backend using the pre-computed mesh format specified by neuroglancer.  The current implementation assumes a single chunk representation for the mesh as the intended use case, for now, is for quick (low-res if needed) browsing.  I otherwise tried to closely conform to the interface used in the precomputed instance in case we want to support mesh chunking in the future.
tslint and clang-format were run on the files.

adds dvid simple key/value mesh support

---

python/neuroglancer/viewer_state.py

the blend mode option seems to be missing in the python bindings
this commit just adds it as an option for `ImageLayer`

add blend mode for python binding

---

src/neuroglancer/layer_panel.css
src/neuroglancer/layer_panel.ts
src/neuroglancer/util/color.ts
src/neuroglancer/util/float32_to_string.spec.ts
src/neuroglancer/util/float32_to_string.ts
src/neuroglancer/widget/coordinate_transform.ts

* Reworked `float_to_minimal_string`
* renamed to `float32_to_string`
* extended explanation, removed round-trip remark (never hold true)
* added unit tests + fixes
* changed behavior to return exponential notation if values become too small.
* Use `float32_to_string` for layer panel values that are representable as float32
* ideally, this should check for the actual datatype of the layer, but I couldn't find it anywhere...
* Increase field size for layer values from 30 to 50 chars
* enough to display equivalence mapping for two UInt64 values
* typically enough to display 3-dimensional Float32 values
Resolves https://github.com/seung-lab/neuroglancer/issues/217

Improved display of multi-channel layer values

---

src/neuroglancer/webgl/colormaps.glsl

Hey all,
I just implemented Dave Green's cubehelix here. It looks absolutely fantastic, so I thought I should share. If you want a quick preview, just paste this as your shader (substitute your chosen amplitude for "40.0" below):
```
void main() {
float x = clamp(toNormalized(getDataValue()) * 40.0, 0.0, 1.0);
float angle = 2.0 * 3.1415926 * (4.0 / 3.0 +  x);
float amp = x * (1.0 - x) / 2.0;
vec3 result;
float cosangle = cos(angle);
float sinangle = sin(angle);
result.r = -0.14861 * cosangle + 1.78277 * sinangle;
result.g = -0.29227 * cosangle + -0.90649 * sinangle;
result.b = 1.97294 * cosangle;
result = clamp(x + amp * result, 0.0, 1.0);
emitRGB(result);
}
```
I have used defaults for some of his parameters (hue, starting color, # of rotations), because I was hesitant about adding them …

Added a cubehelix colormap

---

python/examples/example_action.py
python/neuroglancer/viewer_state.py
src/neuroglancer/layer_specification.ts

This PR changes the "layers" property in the JSON state from an object to an array to preserve the layer order (see https://github.com/seung-lab/neuroglancer/issues/228).

Layer order now preserved on refresh or on load from URL or JSON server

---

python/setup.py

fix(python): Constrain tornado<6 due to sockjs-tornado incompatibility

---

src/neuroglancer/annotation/frontend_source.ts
src/neuroglancer/annotation/index.ts
src/neuroglancer/ui/annotations.ts

Currently all the annotations are removed from the DOM and recreated everytime there is an add/update/delete on a single annotation. This affects performance as the list grows.
This PR aims to avoid that by targeting specific annotations when the list is modified.
There maybe better way to solve this but I think this solution avoids any changes to the core framework.
* Create separate functions and signals for add/update/delete annotation and trigger signals accordingly
* Create interface for common signals between AnnotationSource and MultiscaleAnnotationSource

modify single annotation instead of recreating the entire list

---

src/neuroglancer/viewer.ts

This adds a build option for `defaultViewerOptions`
To overwrite the options on build, run the following command (this one disables the layer dialog):
`npm run build-min -- --define OVERWRITE_DEFAULT_VIEWER_OPTIONS="'showLayerDialog: false, resetStateWhenEmpty: true'"`
Thanks @xgui3783 for your [example](https://github.com/xgui3783/neuroglancer/commit/9453eb1d640b88f723be2f24428239e086edd6ab), which I modified slightly to make the declaration inside `viewer.ts` as well as handle builds which don't specify the default viewer options.
The syntax I'm using to check if it's undefined is a bit ugly -- happy to change to something else if you prefer.
Related to issue https://github.com/google/neuroglancer/issues/147

default viewer build option

---

src/neuroglancer/python_integration/server_connection.ts

A very small tweak to the token parsing in the python client to preserve the path.  The current regex expects the path to be in the form `^/v/<token>/`, which will not work with [Jupyter Server Proxy](https://github.com/jupyterhub/jupyter-server-proxy/).
With Jupyter Server Proxy server extension enabled in jupyter, the normal neuroglancer URL (e.g. `http://127.0.0.1:51119/v/2df69e9395e0adb8b0d14b7dbec99751220625aa/`) can be accessed as  `http://localhost:8888/proxy/51119/v/2df69e9395e0adb8b0d14b7dbec99751220625aa/`.
My goal here is have neuroglancer notebooks working with [binder](https://mybinder.org/), which does not allow remote access to additional ports except through a proxy.

fix(python): work with jupyter-server-proxy

---

src/neuroglancer/datasource/render/backend.ts
src/neuroglancer/datasource/render/frontend.ts

Adds support for uint16 data from render via `?encoding=raw16`, added to render in https://github.com/saalfeldlab/render/pull/100.
Ultimately, I think I'd rather use png for 16-bit, but quickly aborted that effort when looking into the strange world of png libraries in npm.

feat(render): uint16 render support

---

.appveyor.yml

On Windows, recent versions of conda require you to actually 'activate' the base environment, not merely adjust your PATH.
(Explained in conda/conda#8836)

chore: Fix appveyor setup

---

src/neuroglancer/widget/autocomplete.ts

In Firefox, "disabled" disables any interaction with the
layer entry field whereas in Chrome it allows you to select
the text in the box -- a common workflow when using CloudVolume
to grab the layer path.
A standard property "readOnly" is available that works cross-browser.

fix: allow copy pasting layer location in Firefox

---

src/neuroglancer/layer_panel.ts

Fix for #151 
Control + click on Mac works as intended. This makes right click create annotations as well. Alternatively, ⌘+Click can also be used to create annotation layers.

Mac annotation support

---

src/neuroglancer/datasource/index.ts
src/neuroglancer/datasource/precomputed/frontend.ts

This PR adds support for a new key `redirect` to the precomputed info file. If specified, it will work as an automatic layer source redirection. This is useful in order to forward users who use old, bookmarked links to newer versions / formats of the specified layer.
Throws an error if more than 10 redirects occur, or a cycle is detected.
Works for loading existing links, as well as when trying to add layers via the layer dialog.

feat(datasource/precomputed): Layer redirection

---

src/neuroglancer/datasource/precomputed/README.md
src/neuroglancer/datasource/precomputed/frontend.ts

Currently, neuroglancer treats missing mesh info files as legacy
format, but we found that it is necessary to add some attributes
to mesh info files in order to deduplicate chunk boundaries. However,
this leaves us with no way to read legacy formats. Thus, we add
neuroglancer_legacy_mesh as an explicit type to enable continued use.

feat: @type 'neuroglancer_legacy_mesh' triggers legacy mesh format

---

src/neuroglancer/skeleton/decode_swc_skeleton.spec.ts
src/neuroglancer/skeleton/decode_swc_skeleton.ts

This PR is for fixing issue #185. It fixes the parsing order of skeleton coordinates, and handles multiple roots and non-contiguous IDs. It also adds missing license comments.

fix(decode_swc_skeleton): fix several problems in swc parsing

---

src/neuroglancer/datasource/dvid/frontend.ts

This PR cleans up some code in dvid/frontend to remove unnecessary requests of getting data instance info from node level. Such information can be retrieved from previous repo calls. The extra requests were added to handle a bug in DVID that causes missing information at the repo level. Now the bug has been fixed and it's no longer necessary. The fix does not only improve the performance a little bit, but also facilitate future improvement which I will send through more PRs.

fix(datasource/dvid): remove unnecessary calls of getting dvid info

---

src/neuroglancer/datasource/dvid/backend.ts
src/neuroglancer/datasource/dvid/base.ts
src/neuroglancer/datasource/dvid/frontend.ts
src/neuroglancer/datasource/dvid/register_default.ts

This PR adds credentials support for fetching data from DVID. In the current DVID implementation, the default entry point of getting an auto token is <baseUrl>/api/server/token, which is necessary for any DVID server with the https protocol. We also allow the user to set up an auth server in the source url through query strings in case different auth servers are used. Note that DVID does not provide the login process, which must be done through a separate server. We assume that it has the same domain as the auth server and has the pattern 'https://flyemlogin.[domain]/login'. This PR should not affect any DVID layers without auth settings like before.

feat(datasource/dvid): add credentials support for DVID datasource

---

python/neuroglancer/__init__.py
python/neuroglancer/segment_colors.py
python/neuroglancer/viewer_state.py
python/tests/segment_colors_test.py

This feature adds a property: "segment_html_color_dict" to segmentation
layers via the Python API. The property returns a dictionary where
keys are segment ids and values are the html color codes,
e.g. #F9F607 (yellow) corresponding to each currently selected segment.
The colors are the same as what is rendered in the viewer for the segments,
given a color seed. This property uses the current color seed when
calculating the color codes.

html colors for selected segments in Python API

---

python/neuroglancer/server.py
python/setup.py

The following fix should make sockjs-tornado compatible with tornado6
https://github.com/mrjoes/sockjs-tornado/pull/118

Remove tornado<6 dep constraint

---

src/neuroglancer/datasource/n5/frontend.ts

Public on AWS with GetObject but not ListObject permissions will get a 403 instead of 404 when a files does not exist.
This prevents access to n5 volumes with a fatal error when the first missing `attributes.json` gets a 403 response.
(This is from debugging access to a s3 hosted n5 volume with @sharmishtaa).

n5: work with AWS (403 instead of 404)

---

README.md

Link in README is missing `/ui/` and results in a 404.

Fix link to input bindings in README

---

src/neuroglancer/widget/range.css

A possible fix for https://github.com/google/neuroglancer/issues/245 .
The sliders now look like this with FireFox 80 on MacOS dark mode:
These changes appear to have no effect on MacOS Chrome. I have not tested on Windows or Linux.

Make range track visible on FireFox 80/81 on MacOS.

---

src/neuroglancer/annotation/backend.ts

In [sendCommitRequest](https://github.com/google/neuroglancer/blob/2e4a2c18705de6dc3a6e9cfbc441bac4230c82cb/src/neuroglancer/annotation/frontend_source.ts#L474), `annotationId` is undefined in the case of adding an annotation, causing an undefined `annotationId` in the message for the error handling. This can keep [handleFailedUpdate](https://github.com/google/neuroglancer/blob/2e4a2c18705de6dc3a6e9cfbc441bac4230c82cb/src/neuroglancer/annotation/frontend_source.ts#L680) in annotation/frontend_source.ts from  showing the right error message because `localUpdate` will always be undefined in this case. As a result, the status message will get stuck at 'Committing annotations' when adding an annotation fails.
This pr tries to fix this problem by including the new annotation id in the error …

Include the right annotation id for error handling

---

src/neuroglancer/datasource/python/backend.ts
src/neuroglancer/datasource/python/frontend.ts

As @chrisroat noticed in the comment thread of #150, local data sources are no longer working through [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy).  The problem stems from the root-relative URLs.
An example URL for neuroglancer with jupyter-server-proxy would be `http://localhost:8888/proxy/58060/v/f9dd9e35803d93ee67997951bf4a138a9abb7983/`
This PR is a quick & dirty fix illustrating the problem. I'm not sure what a proper @jbms solution would be. 🙂
I know this worked ~1-2 years ago. Were the data URLs previously under the token?

Use relative paths for python data source.

---

src/neuroglancer/datasource/precomputed/volume.md

The current algorithm adds an extra bit for grid sizes that are a power of 2.  This was discovered by me and @william-silversmith when I was debugging grids of that size.  I was seeing missing/swapped data when reading sharded tensorstore datasets with cloud-volume, which had implemented the current version of the algorithm.  See https://github.com/seung-lab/cloud-volume/pull/482

Update compressed morton code algorithm

---

src/neuroglancer/util/http_path_completion.ts

This patch allows the Content-Type header to have any case
and also allows charset specification, like so:
`Content-type: text/html; charset=UTF-8`
which wasn't allowed before

http_path_completion: Loosens check for content-type

---

src/neuroglancer/ui/tool.ts
src/neuroglancer/viewer.ts

This is part of the seung-lab merge project.
For some tools (such as merge and split), it is more convenient to have the tool be activated by toggle (press and release the key once to activate, then press and release the key again to deactivate) rather than hold (press the key to activate, then release the key to deactivate). This PR adds a `toggle` parameter (defaulting to `false`) in the `Tool` constructor which supports this behavior. To preserve default behavior, I don't set this to `true` for any currently existing tools, but I could if you think that's a good idea (it would be a small change to `MergeSegmentsTool` and `SplitSegmentsTool`, or any other tool you think would be suited to this behavior).
It also makes the `deactivate` method on the `ToolBinder` public. This is needed …

Support toggle activation for tools

---

src/neuroglancer/sliceview/compresso/index.ts

Check was backwards compatible, but not forwards compatible with
the new version. Validated that this works with latest.

fix(compresso): format check was incorrect

---

README.md

Hi Jeremy,
If this is okay, I'd like to add Igneous to the related projects section to make it easier for people to find it. It might help people get started with Neuroglancer more quickly.

docs: add Igneous to related projects

---

src/neuroglancer/datasource/boss/frontend.ts

BossDB can render u8 imagery as JPEG filmstrips, which saves ~50% on egress filesize. All other datatypes should be returned as npygz.
This also adds support for non-u8 imagery :)
> cc @BrockWester @dxenes1 @hannahgooden

Choose best available BossDB requested encoding

---

src/neuroglancer/datasource/graphene/frontend.ts

rather than waiting for response to return full mouse control to the user

fix(datasource/graphene): closing graphene merge on submission

---

src/neuroglancer/datasource/precomputed/frontend.ts
src/neuroglancer/datasource/precomputed/volume.md

Hi Jeremy, 
I've been following the thread between you and Chris on #446 and wanted to offer this PR as a potential solution to the placeholder issue we're having with the FAFB dataset. Feel free to disregard it if you have a better solution in mind!
This PR adds an optional boolean `hidden` attribute to the ScaleInfo. If a scale is hidden, it is filtered out when creating the nested arrays for `getSources`. However, the base resolution is still set on the first scale, regardless if it's hidden. It's similar to Chris's implementation of 'placeholder' on the seung-lab fork. 
Thank you for your time and consideration!

feat: adds hidden attribute to ScaleInfo for placeholder resolutions

---

src/neuroglancer/annotation/annotation_layer_state.ts
src/neuroglancer/annotation/frontend_source.ts
src/neuroglancer/annotation/index.ts
src/neuroglancer/datasource/graphene/frontend.ts
src/neuroglancer/datasource/graphene/graphene.css
src/neuroglancer/perspective_view/panel.ts
src/neuroglancer/ui/annotations.ts
src/neuroglancer/ui/segment_list.ts
src/neuroglancer/webgl/offscreen.ts

Changes to merge tool:
* can now queue up multiple merges and bulk submit them
* pending merges are now better visualized as line segments
I also disabled the default graph tools in the segmentation tab if the graph source provides its own tab. That has tricked many of our users.
As you discussed with Sven, there was issues when adding a line segment in 3d. The easiest solution I could find was disabling the pick buffer by calling gl.drawBuffers before and after rendering an annotation layer though I am not so familiar with the nuts and bolts of open/webgl.
graphene prefers a base segment when submitting a merge so I made it available via the line segment by added a getBase option to getSelectedAssociatedSegments. It doesn't integrate as cleanly as I'd prefer.

feat(datasource/graphene) improved merge tool

---

src/neuroglancer/annotation/type_handler.ts

It's listed in [the docs](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/annotation/rendering.md#point-annotations), but was missing from the overload set.

annotation: add missing overload for setPointMarkerColor(vec3)

---

src/neuroglancer/datasource/n5/README.md

This README is the best documentation of the BDV / N5viewer metadata I keep referring to, so I thought I'd help get rid of some red squigglies.

N5 datasource docs JSON fix

---

src/neuroglancer/annotation/user_layer.ts

after changing a layer source for a layer that has an actively linked relationship. This prevented it from showing the spatial index for the new source until the page was refreshed.
Example:
https://cj-cave-anno-share-dot-neuroglancer-dot-seung-lab.appspot.com/#!middleauth+https://global.daf-apis.com/nglstate/api/v1/6105906074877952
Go to the source tab on the active layer, replace the source with `cave://middleauth+https://minnie.microns-daf.com/materialize/api/v3/datastack/minnie65_phase3_v1/table/column_atype`. Wait a few seconds and nothing will appear. Refresh the page and the `column_atype` data will appear.
This is just one solution and it does have the drawback that you lose the relationship state for a layer if you want to return to it.

fix(annotation): fully deleting old relationships to allow displayUnfiltered to update properly

---

src/neuroglancer/webgl/empirical_cdf.ts

The old one doesn't work any more. The new one works, and points to the personal website of the publication author.

Fix link in docstring

---

src/neuroglancer/chunk_manager/frontend.ts
src/neuroglancer/datasource/graphene/backend.ts
src/neuroglancer/datasource/graphene/base.ts
src/neuroglancer/datasource/graphene/frontend.ts

Replaces https://github.com/google/neuroglancer/pull/450
With our current infrastructure, the only way for us to get mesh updates is to continuously poll the manifest endpoint to see if it changes, we can't rely on 404 responses as previously thought. Eventually we want to get push messages on the client to replace this logic.
I was asked to try to reduce the flicker that occurs when we change the manifest of an existing cell. I have partial "fix" with this commit 80d95e103c3a03bc04e338371455939dfb233cab. The issue is that the ManifestChunk arrives before the first FragmentChunk.
The easiest solution that mostly works is to prevent ManifestChunks from triggering redraws. I was surprised that ManfestChunk gets a GPU_MEMORY state. It still can cause issues.
Do you have any suggestions on …

feat(datasource/graphene) auto reloading graphene manifest after an edit

---

src/neuroglancer/datasource/state_share.ts

due to chrome introducing restrictions on setting protocols using the URL API
```ts
const x = new URL('http://google.com');
x.protocol = 'middleauth+https:';
```
The second line is silently rejected in chrome 118.

fix(state_share): new method to include credentials for state sharing

---

biome.json
src/ui/side_panel.ts

```
✖ Avoid the delete operator which can impact performance.
282 │   endDrag() {
> 283 │     delete this.element.dataset.neuroglancerSidePanelDrag;
│     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
284 │     this.dragSource = undefined;
285 │   }
ℹ Unsafe fix: Use an undefined assignment instead.
281 281 │   
282 282 │     endDrag() {
283     │ - ····delete·this.element.dataset.neuroglancerSidePanelDrag;
283 │ + ····this.element.dataset.neuroglancerSidePanelDrag·=·undefined;
284 284 │       this.dragSource = undefined;
285 285 │     }
```
Using undefined causes the data attribute to remain as ```data-neuroglancer-side-panel-drag="undefined"``` which still triggers the [data-neuroglancer-side-panel-drag] css property which makes the neuroglancer-side-panel-drop-zone block …

fix(ui/side_panel) biome linter broke drag end handler

---

src/ui/annotations.css
src/ui/annotations.ts

In trying to use neuroglancer to browse precomputed annotations I often want to see what the annotation is that I'm mousing over, and perhaps grab its ID or other metadata that is displayed to my clipboard. 
This PR adds the annotation ID to the list of properties that are displayed and modifies the CSS to make neuroglancer-properties selectable by users so that users can copy/paste properties to their clipboard.

feature: add annotation ID and make properties selectable

---

src/segmentation_display_state/property_map.ts
src/ui/segment_list.ts

tag descriptions were not displayed to the user anywhere, so i've added those. 
Also, for long tag lists there wasn't a good way to search through the tags. 
This implementation assumes that if there were no results from the regexp search in the segment labels that the user might also want to search through the tags and tag descriptions and limit that list instead.

Feature: adds display of tag descriptions and regexp searching for tags

---

src/layer/segmentation/index.ts
src/mesh/frontend.ts

finds the closest loaded associated mesh vertex to the global position
I also did an implementation that just returns the first vertex (in the order that I iterate through them here) and one where it finds the vertex closest to the mean vertex position. I still need to get some feedback to confirm if this is preferred but this seems to be ideal as it minimizes movement.
I might be making an assumption on using vertexPositions. The type is `EncodedVertexPositions` but it seems to be work without any kind of decoding.
I'm not using localPosition when comparing the globalPosition with the vertexPositions, only globalToRenderLayerDimensions and transform.modelToRenderLayerTransform. I tried to do the inverse of how globalPosition is modified in moveToSegment but I am a little confused why I …

feat(segmentation_user_layer) implemented getObjectPosition for MeshLayer

---

src/util/uint64.spec.ts
src/util/uint64.ts

https://github.com/google/neuroglancer/blob/daf82f3ad4af2007e96faca35143cd5ec986bf60/src/util/uint64.ts#L105
if vHigh > `Number.MAX_SAFE_INTEGER / 0x100000000`
`vHigh *= trueBase;` will exceed Number.MAX_SAFE_INTEGER.
`Math.floor(vHigh / lowBase)` will then start to return whole numbers when the fraction is very close to 0 or 1. When it is due to it being 1, javascript rounds up which then causes the floor operation to fail. BigInt safely handle the division + floor operation.
For example:
base 3, low 0, high 92064593
92064593 * trueBase / 3486784401 = 113403746.99999998652053164327...
```
92064593 * trueBase / 3486784401 = 113403747 (in javascript)
Math.floor(92064593 * trueBase / lowBase) = 113403747
92064593 * trueBase % lowBase = 3486784382
```

fix(uint64): avoid rounding errors in Uint64.toString with large high values

---

python/neuroglancer/__init__.py
python/neuroglancer/viewer_state.py
src/perspective_view/panel.ts
src/perspective_view/render_layer.ts
src/volume_rendering/volume_render_layer.ts

Fixes:
1. Picking layer from VR max projection set to `< 1` so as not to interfere with a real annotation with value `1`.
2. Max projection layer uses OIT blending so as not to be layer-order dependent with multiple max-projection layers.
3. Calling `emitIntensity` always overwrites the intensity.
4. Accidental redraw of opaque layers removed.

Volume rendering fixes for max projection - picking, blending, and performance

---

src/webgl/shader_ui_controls.ts

Fix accidental passing of actual default value into the trackable transfer function validator function. Now correctly passes the copy of the default value to the validator.
Impact: previously if the JSON contained information about the default color, or the window, but not about the transfer function points, the points wouldn't get tracked in the JSON state correctly anymore in some cases.

fix: update transfer function points in JSON in all cases

---

src/ui/layer_data_sources_tab.css

https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B6.000000000000001e-9%2C%22m%22%5D%2C%22y%22:%5B6.000000000000001e-9%2C%22m%22%5D%2C%22z%22:%5B3.0000000000000004e-8%2C%22m%22%5D%7D%2C%22position%22:%5B5523.99072265625%2C8538.9384765625%2C1198.0423583984375%5D%2C%22crossSectionScale%22:3.7621853549999242%2C%22projectionOrientation%22:%5B-0.0040475670248270035%2C-0.9566215872764587%2C-0.22688281536102295%2C-0.18271005153656006%5D%2C%22projectionScale%22:4699.372698097029%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%22precomputed://gs://neuroglancer-public-data/kasthuri2011/ground_truth%22%2C%22tab%22:%22source%22%2C%22panels%22:%5B%7B%22row%22:1%2C%22flex%22:1.6%2C%22tab%22:%22segments%22%2C%22tabs%22:%5B%22segments%22%5D%7D%5D%2C%22selectedAlph …

fix(ui): increase z-index for layer data source dropdowns, which were appearing below pinned panels

---

build_tools/build-package.ts
package.json

esbuild does not support generating declaration files https://github.com/evanw/esbuild/issues/95

chore: output declaration files for neuroglancer packages

---

src/widget/transfer_function.ts

Previously, the auto range could get computed as `[point_x_value, 1]` where `point_x_value > 1` with only one point, which would cause incorrect transfer function calculations. This could only happen for float32 datasets. This is to correct for this, by setting the range to `[point_x_value, point_x_value + 1]` for single point transfer functions and float32 data.

Fix: automatic range computation in transfer functions for float32 datasets no longer fails for one point

---

python/neuroglancer/viewer_state.py
src/data_panel_layout.ts
src/display_context.ts
src/layer_group_viewer.ts
src/layer_groups_layout.ts
src/perspective_view/panel.ts
src/rendered_data_panel.ts
src/ui/viewer_settings.ts
src/util/framerate.spec.ts
src/util/framerate.ts
src/viewer.ts
src/volume_rendering/volume_render_layer.ts
src/webgl/offscreen.ts

The overall idea is that a setting (currently on by default) would allow a global downsampling in XY resolution for 3D panels of transparent layers during camera movement if the framerate drops below a certain threshold.
All of this is open to change, but currently:
Target FPS is 60
The mean framerate over a running 6 frames after a camera move is initiated is calculated
If this median framerate drops below 60, a downsampling rate of 2, 4, or 8 is chosen based on how far from 60 the framerate is.
If a downsample is detected, then during this camera movement, the downsampling rate will never go back above the highest downsample rate detected for about the last second
When the camera stops moving, a fresh full resolution drawing is requested after 300ms
To update:
1. Only DS for VR, new …

Feature - adaptive downsampling of volume rendering based on framerate

---

src/kvstore/special/index.ts

Some static file servers (e.g., the nodejs program [`serve`](https://github.com/vercel/serve)) will handle a successful HTTP range request (i.e., status code 206) _without_ including a `content-range` header in that response. Perhaps `content-range` is omitted because it's not on the list of [CORS safelisted response headers](https://developer.mozilla.org/en-US/docs/Glossary/CORS-safelisted_response_header), but that's just a guess. This impairs neuroglancer's ability to read sharded zarr v3 chunks when the shard index is configured to reside at the end of a chunk, as in this case neuroglancer makes a GET with a suffixLength byte range request but if the response from the server does not include the `content-length` header, it's not possible to resolve an offset + length representation of …

fix(datasource/zarr) `HEAD` to get content length

---

src/datasource/middleauth/credentials_provider.ts
src/status.css
src/status.ts

I tried to be unopinionated with the styling, keeping it minimal/using original status message styling. I am not blocking any input while the modal is up. Multiple modals at the same time get arranged in a list from oldest to newest. Perhaps I should reverse the order.

feat(status): add modal status message option that can be closed back to a normal status message

---

package-lock.json
package.json

Fix #625
Upgrade numcodecs.js to version 0.3.2
Version 0.3.2 incorporates https://github.com/manzt/numcodecs.js/pull/47 which supports detection of 
`ZSTD_CONTENTSIZE_UNKNOWN` from `ZSTD_getFrameContentSize`.
Zstd decompression is now handled via the advanced streaming API so that the entire buffer size does
not need to be known ahead of time.
Incorporating this allows Neuroglancer to read Zstd compressed data from Tensorstore. However, this not resolve 
https://github.com/google/tensorstore/issues/182 . Other Zarr implementations such as zarr-python continue to 
have issues:
https://github.com/zarr-developers/zarr-python/issues/2056

fix(zstd): Upgrade numcodecs.js to 0.3.2 for Zstd streaming decompression

---

src/volume_rendering/volume_render_layer.ts

Included also in #614 as changes along these lines are needed for that PR.
The histogram computation in volume rendering has been fixed for unequal chunk sizes to both:
1. Pass the correct chunk size to the data sampling shader per chunk
2. Distribute the total number of samples for the histogram according to the percentage of the total chunk volume that each chunk takes up. E.g. with 1k samples overall, total chunk volume of 10k voxels, and a single chunk with 1k voxels, we would aim to obtain 100 random samples from that chunk for the histogram. While for a chunk with 300 voxels, we would aim for 30 random samples from that chunk for the histogram.
In addition, the 3D histogram calculation no longer discards values at exactly 0 after invlerp. The previous behaviour was due to mistaking …

fix(volume-rendering): correct data access for histogram in volume rendering with unequal chunk sizes

---

src/ui/url_hash_binding.ts

without a maxWait value, debounce can cause important state changes to be lost if there is high rate of state change between the important change and a page reload
mouse movement causes state changes and is probably the main reason this can happen. I just threw in a value of double the debounce delay.
Alternatively, we could use throttle with the trailing option set to true. This should give the same behavior as using a maxWait value of updateDelayMilliseconds but maxWait allows more control with performance tuning.

fix(url_hash_bindings): added debouce maxWait value for throttledSetUrlHash

---

src/display_context.ts
src/util/framerate.ts

Summary: improved handling of gl query errors that could cause failed queries to hang around in the pool and decrease frame time tracking accuracy
In some cases the query handling for frame deltas was not properly accounting for errors in the queries. This could lead to some old queries get left in the query pool for a long time, and warnings in the console about trying to start the same query multiple times, or fetching from a query that never started.
To address this, the main changes are:
1. Keep track of the query started and ended state manually in the code. The state from gl is also checked, but if we know that the query never started or ended for some reason, we can avoid triggering a gl error trying to get results from that query - and instead delete the failed query.
2. Keep the …

fix(framerate tracking): better handling of query failures

---

src/widget/virtual_list.ts

Use the existing `debounceUpdateView()` in place of just `updateView()` for the `resizeObserver()`, similar to other updates in the class.
When embedding Neuroglancer in an React app, the lack of debounce causes an infinite update loop and it will not load.

fix(virtual_lists) use existing debounceUpdateView with resize observer

---

src/widget/icon.css

…when hovering inside the ikonate svg with a default title. Previously you would only see the correct title if you hovered in the tiny margin surrounding the svg.
Tested on chrome and firefox
Before:
After:

fix(ui): buttons now display the title set in the makeIcon options

---

.github/workflows/build.yml

Seems to be related to https://github.com/actions/setup-python/issues/809.

chore(github): disable pip upgrade to fix github actions workflow

---

src/layer/index.ts
src/shared_disjoint_sets.ts

also removed disposed method on SharedDisjointUint64Sets to prevent potential "cannot read properties of undefined" errors as garbage collection benefit is likely insignificant
replaces https://github.com/google/neuroglancer/pull/664

fix(layer): ensure layer references are unset when the associated layer is deleted

---

src/datasource/zarr/frontend.ts
src/datasource/zarr/ome.ts

[RFC-2](https://ngff.openmicroscopy.org/rfc/2) has now been adopted. In preparation for the OME-Zarr 0.5 release, this PR wraps the NGFF metadata in the Zarr metadata within an "ome" block. This checks for that block and if it exists unwraps the necessary metadata if the Zarr version is 3.
Originally opened as #616 
cc: @normanrz

ome.ts: update with ome-zarr 0.5

---

python/neuroglancer/coordinate_space.py
python/neuroglancer/write_annotations.py
python/tests/n5_test.py
python/tests/zarr_test.py
src/datasource/n5/backend.ts
src/datasource/n5/base.ts
src/datasource/n5/frontend.ts
src/datasource/nifti/backend.ts
src/datasource/precomputed/backend.ts
src/datasource/zarr/codec/gzip/decode.ts
src/datasource/zarr/codec/gzip/resolve.ts
src/datasource/zarr/metadata/parse.ts
src/sliceview/backend_chunk_decoders/bossNpz.ts
src/sliceview/backend_chunk_decoders/ndstoreNpz.ts
src/util/gzip.ts

This was accidentally broken by the change to use `CompressionStream`.
Fixes https://github.com/google/neuroglancer/issues/679.

fix(gzip): Fix decoding of zlib-format data

---

.oxlintrc.json
eslint.config.js
package-lock.json
package.json
src/annotation/bounding_box.ts
src/annotation/frontend_source.ts
src/annotation/renderlayer.ts
src/annotation/type_handler.ts
src/axes_lines.ts
src/datasource/enabled_backend_modules.ts
src/datasource/precomputed/frontend.ts
src/mesh/frontend.ts
src/single_mesh/frontend.ts
src/skeleton/frontend.ts
src/ui/tool_palette.ts
src/volume_rendering/volume_render_layer.ts
src/webgl/buffer.ts
src/webgl/index_emulation.ts
src/webgl/spheres.ts
src/webgl/vertex_id.ts
src/widget/transfer_function.ts
tests/kvstore/zip.spec.ts

oxlint is much faster than eslint, completing in about 0.5 seconds, compared to eslint completing in about 15 seconds. It is still missing some important rules, but critically, it supports "import/no-cycle", which is the one rule that is incompatible with per-file caching. Consequently, eslint can now be run with caching enabled, which greatly improves iteration time.

chore(lint): Use oxlint in addition to eslint

---

src/widget/position_widget.ts

`EventAction` is an unused import -- in which type-checking fails when running `npm run dev-server` locally -- simple PR to remove import until it is either used or intentionally removed
This issue persisted when trying on [node >= 22](https://github.com/google/neuroglancer/blob/master/package.json#L10-L12) (verified locally via `nvm use 22` and `nvm use 23`)
Cc @kabilar

Remove EventAction import to resolve dev-server compilation error

---

README.md

Adds panel-neuroglancer to readme list of related projects. 
- [Panel-Neuroglancer](https://github.com/panel-extensions/panel-neuroglancer) - Integrate Neuroglancer into Jupyter notebook workflows and Python web apps with this HoloViz Panel extension.
Relevant to discussion in, and essentially closes https://github.com/google/neuroglancer/issues/554
I have signed the Google CLA

Add panel-neuroglancer to readme list of related projects

---

src/coordinate_transform.spec.ts
src/coordinate_transform.ts

Previously, coordinate bounds approximately, but not exactly, equal to an integer or half-integer were handled poorly.
In particular, the lower/upper bounds could end up off by 1 from the expected value, and voxelCenterAtIntegerCoordinates could end up false when it was expected to be true, leading to coordinates snapping to the boundary between two voxels, rather than the center, as expected.
With this change, coordinate bounds within 1e-3 of an integer or half-integer are handled properly.
Fixes https://github.com/google/neuroglancer/issues/719.

fix(coordinate_space): handle nearly integer-aligned bounds

---

src/chunk_manager/generic_file_source.ts

This fixes the following error reported at
https://github.com/google/neuroglancer/issues/743
frontend.ts:328 Uncaught TypeError: Cannot read properties of undefined (reading 'chunkManager')
at updateChunk (frontend.ts:328:31) # webpack://neuroglancer/src/chunk_manager/frontend.ts
at RPC.<anonymous> (frontend.ts:348:3)
at RPC.target.onmessage (worker_rpc.ts:174:40)

fix(AsyncCache): fix bug when freeing an async cache entry

---

src/help/input_event_bindings.ts
src/util/event_action_map.ts

Previously, optional modifiers in a binding like
"alt?+control?+shift+keya" would result in 4 separate help entries for each of the 4 combinations.
With this change, the optional modifiers are excluded altogether, as they already were from the binding tooltips, resulting in a single help entry for "shift+keya".
Additionally, patterns like "shift+key[a-z]" -> "tool-[A-Z]" and "[1-9]" -> "toggle-layer-[1-9]" resulted in each binding being displayed separately.  With this change, the pattern is recognized and displayed as a single entry.
These changes together make the help display much, much more concise.

feat(help/input_event_bindings): Simplify input event binding help display

---

src/ui/layer_list_panel.css
src/ui/layer_list_panel.ts

The layer list panel number width is determined by the number of characters in the highest number non-archived layer. Since archived layers didn't contribute to the layer count for determining the width for the layer list panel numbers, it could result in cases like this where the number would overlap the visibility icon for archived layers:
We're thinking to change the count here to take all layers into account so that archived layer numbers don't overlap the visibility icon and be like this:
Maybe there is some reason though that archived layers were previously excluded for the number width count that we should be considering here? For example, maybe the layer numbers were intended to be hidden for all archived layers. If so, happy to amend this to account for that, thanks

fix(UI - layer_list_panel): Change layer number width spacing to consider archived layers

---

python/neuroglancer/viewer_config_state.py
src/viewer.ts

Accidentally the ability to hide the screenshot button was left out when we made the PR for the screenshot from the UI.
I've updated this to allow for it to be hidden, and also hidden from Python. Please let me know if there is anything else that should change for this, and sorry it was left out in the first place!

fix: camera screenshot icon can hide like other icons in top bar

---

python/neuroglancer/viewer_config_state.py
src/viewer.ts

During the creation of the changes for the screenshot show/hide from UI that were left out, I noticed https://github.com/google/neuroglancer/issues/439
The idea of a `showTopBar` came up there, which would show/hide the entire top bar as opposed to have to individually set each control visibility.
Maybe this would enable that behaviour in the intended way? Let me know what you think

feat: ability to show/hide the whole top bar in one setting

---

src/display_context.ts

Previously, panels for Python prefetch states inadvertently did not have their bounds correctly calculated, leading to a width and height of zero, which meant that data was not correctly prefetched.

fix(python/prefetch): use non-zero width/height for prefetching

---

src/rendered_data_panel.ts

I think this is the check that is needed to stop precomputed data format annotations from being moved

Fix(move-annotation): include a check for layer source readonly on move-annotation action

---

src/widget/invlerp.ts
src/widget/transfer_function.ts

We are using `neuroglancer` as a library in a project. The project is split in two, a main project and a sub-project, the main project uses the sub-project that defines a react wrapper around neuroglancer. This sub-project, setup/built using vite, is the one that uses `neuroglancer` as a library (the main project uses Remix)
At some point, when loading an URL with an `img` layer, the panel created try to initialize a invertlp widget. This component tries to access the webgl element from the context, but cannot because the context is undefined. It comes from here (see the screenshot below), in the constructor, there is a call to super(`e.display`), and `e.display` is `undefined`.
This comes from the way this caller code is compiled:
```typescript
export class InvlerpWidget extends Tab { …
```

fix: move some attribute initialization from class level to constructor

---

src/layer/annotation/index.ts

The show/hide code viewer feature for the shadder for annotations is not hidding the properties of the shadder when hidding the code editor.
This PR hides also the shadder properties when the shadder code editor is hidden

feat: Show/hide the shadder properties for the annotation layer depending on the code visibility

---

src/datasource/render/backend.ts
src/datasource/render/base.ts
src/datasource/render/frontend.ts

Hi, I'm a software engineer at HHMI/Janelia working on [Render](https://github.com/saalfeldlab/render). Neuroglancer is an integral part of our EM-reconstruction pipeline and this PR updates the Render datasource to better align with the current capabilities of the Render web service. The key changes are:
1. **Improved support for optional query parameters** specified in the datasource url in the format ?key=value, which are now forwarded directly to the Render web service rather than being hardcoded in neuroglancer. This allows support for parameters introduced in recent versions or forks, without any changes to the existing url syntax. 
2. **Autocompletion for query parameters** was added by dynamically fetching the Swagger schema of the Render service. This improves discoverability and …

Expand render datasource functionality

---

src/ui/layer_data_sources_tab.css

With a tool palette open and a layer side panel above it, clicking the data source dropdown causes it to overlap with the group name because it is with the same z-index and sticky
I've bumped up the z-index on the data source here to make it sit over it

fix(ui): bump z-index for data source to make it go over tool palettes

---

python/examples/write_annotations.py
python/neuroglancer/write_annotations.py

You could specify the defaults in the property spec but then from what I can see they didn't inform the property values when using the writer.
Here, the idea is that the defaults are the starting point for the values, and if the user specifies a new value when adding an object that property is overridden.
One thing that was a little awkward was that you had to specify the default of a color type in the spec as a string, but then when you used that property (such as in `add_point`) you had to provide a tuple of uint8s. This was a bit confusing, so now you can pass hex strings when using `add_point` or similar. You still have to define the default value as a hex string though.
Also updates the writer example to show more properties being written.

fix(python): annotation writer uses default values

---

src/widget/position_widget.ts

Previously the tool palette dimension playback velocity input was disabled
I guess this was because the tool which shows on keybind intended to have that input disabled, but I think it's not really possible to change it there anyway from the input

fix: allow tool palette dim tool to set playback velocity

---

src/skeleton/frontend.ts

Previously, the shader read the attribute for the opposing vertex of each line segment.
I noticed with https://github.com/google/neuroglancer/pull/820 that the lines were getting drawn with inverse of the expected width change. It seems pretty clear to me now that this is the correct calculation.
getLineEndpointIndex returns 0 for vertexA (aVertexIndex.x) and 1 for vertexB (aVertexIndex.y) so to use vertexA we need 1 - getLineEndpointIndex and getLineEndpointIndex for vertexB.

fix(skeleton): read/expose the correct custom attribute associated with each vertex

---

src/layer/annotation/index.ts
src/layer/segmentation/index.ts
src/skeleton/frontend.ts
src/ui/segmentation_display_options_tab.ts

Also made the properties available in the shader via `prop_{identifier}()` to match annotation layer behavior

feat(skeleton): display available shader properties above the skeleton shader editor to match annotation layer behavior
