google/neuroglancer

python/neuroglancer/downsample_scales.py
python/neuroglancer/volume.py
python/setup.py

a few tiny tweaks to start with the python3 compatiblity

basic py3 compatibility tweaks

---

src/neuroglancer/datasource/brainmaps/api.ts
src/neuroglancer/datasource/brainmaps/backend.ts

Requires a backend redeployment to work.

Update skeleton handling to use new binary endpoint

---

src/neuroglancer/datasource/dvid/backend.ts
src/neuroglancer/datasource/dvid/base.ts
src/neuroglancer/datasource/dvid/frontend.ts

These are some updates to the dvid datasource that have piled up. With our latest data release at emdata.janelia.org, it's a good time to get these changes back to the main repo.

Dvid backend updates

---

src/neuroglancer/layout.ts
src/neuroglancer/viewer.ts

Defaults to showing the full display. Also fixes noimplicitany error in layout.ts=>Handler

Added options to hide certain UI elements

---

src/neuroglancer/sliceview/volume/renderlayer.ts

Just a syntax error in one of the variable names. I think everything else is identical to the vertex shader and working.

Fix sliceview debug mode

---

.gitignore
src/neuroglancer/rendered_data_panel.ts
src/neuroglancer/segmentation_display_state/backend.ts
src/neuroglancer/segmentation_display_state/base.ts
src/neuroglancer/segmentation_display_state/frontend.ts
src/neuroglancer/segmentation_user_layer.ts
src/neuroglancer/sliceview/volume/segmentation_renderlayer.ts
src/neuroglancer/uint64_set.ts
src/neuroglancer/util/colorspace.ts

Small changes necessary for Wintermute:
1) Color saturation (with widget)
2) Highlights

(Feat): Saturation and highlighting

---

cors_webserver.py

Fixes #94 - cors_webserver port needs to be type "int".

---

src/neuroglancer/annotation/bounding_box.ts
src/neuroglancer/annotation/ellipsoid.ts
src/neuroglancer/annotation/index.ts
src/neuroglancer/annotation/line.ts
src/neuroglancer/annotation/point.ts
src/neuroglancer/annotation/renderlayer.ts
src/neuroglancer/annotation/type_handler.ts
src/neuroglancer/annotation/user_layer.ts
src/neuroglancer/display_context.ts
src/neuroglancer/layer.ts
src/neuroglancer/perspective_view/panel.ts
src/neuroglancer/rendered_data_panel.ts
src/neuroglancer/sliceview/panel.ts
src/neuroglancer/ui/default_input_event_bindings.ts
src/neuroglancer/util/mouse_drag.ts

This PR allows the user to move annotations once they have been placed in both 2d slice views and 3d perspective views, presently via a alt+right mouse click drag.

Moveable annotations

---

src/neuroglancer/data_panel_layout.css
src/neuroglancer/data_panel_layout.ts
src/neuroglancer/perspective_view/panel.ts
src/neuroglancer/rendered_data_panel.css
src/neuroglancer/rendered_data_panel.ts
src/neuroglancer/sliceview/panel.ts
src/neuroglancer/ui/default_input_event_bindings.ts
src/neuroglancer/util/event_action_map.ts
src/neuroglancer/util/keyboard_bindings.ts
src/neuroglancer/util/mouse_bindings.ts
src/neuroglancer/util/mouse_drag.ts
src/neuroglancer/util/touch_bindings.ts

Adds touch controls to Neuroglancer.

Touch controls

---

config/webpack_helpers.js
package.json
python/neuroglancer/static/__init__.py
python/setup.py
src/neuroglancer/datasource/computed/backend.ts
src/neuroglancer/datasource/computed/tensorflow/backend.ts
src/neuroglancer/datasource/computed/tensorflow/base.ts
src/neuroglancer/datasource/computed/tensorflow/frontend.ts
src/neuroglancer/datasource/computed/tensorflow/register_default.ts
tsconfig.json

Adds a computation for the computed datasource that supports Tensorflow.js model inference.

Feat(datasource/computed): Tensorflow.js computation

---

python/examples/flood_filling_simulation.py
python/examples/interactive_inference.py
python/examples/jupyter-notebook-demo.ipynb

Gets CloudVolume based examples working.

Add provenance={} for CloudVolume version sync.

---

src/neuroglancer/skeleton/frontend.ts

Same as in 97c522bf1271f24ba29baef34ca4d5035eb5dd98

fix(skeleton): fix regression in client-side equivalences rendering

---

src/neuroglancer/annotation/frontend_source.ts

This PR for fixing a bug in the updateAnnotation function in annotation/frontend_source.ts. 
In the original code, offsets of types are updated no matter if the passed annotation is new. The problem can be triggered by painting a multi-point annotation. For example, when painting line segment, moving pointB following the mouse cursor before putting it down can keep adding offsets to type AXIS_ALIGNED_BOUNDING_BOX and ELLIPSOID, resulting in wrong offsets for these two types. In this fix I moved offset update inside the annotation existing condition check so that the offsets are updated only when the annotation hasn't been recorded.

fix(annotation/frontend_source): update offsets for new annotation only

---

src/neuroglancer/datasource/precomputed/volume.md

Added more complete bit-wise explanation of standard and compressed morton code and how it improves the ability to handle asymmetric volumes.

Improve compressed morton code explanation

---

README.md

Add bullet in README about [multiresolution-mesh-creator](https://github.com/janelia-cosem/multiresolution-mesh-creator) for generating multi-resolution meshes.

docs: update related projects to include multiresolution-mesh-creator

---

python/neuroglancer/viewer_state.py
src/neuroglancer/segmentation_user_layer.ts
src/neuroglancer/ui/segment_list.ts
src/neuroglancer/ui/segment_select_tools.ts
src/neuroglancer/util/keyboard_bindings.ts

This pr adds tools for selecting/deselecting segments by mouse moving. The tools are added in the seg panel and can be triggered by key binding like other tools.

feat(segmentation_user_layer): adds segment selection tool

---

src/neuroglancer/util/mouse_bindings.ts

fix(mouse_bindings): Fix control+mousedown1 support on macOS Firefox

---

python/neuroglancer/__init__.py
python/neuroglancer/boss_credentials.py
python/neuroglancer/default_credentials_manager.py
src/neuroglancer/datasource/boss/api.ts
src/neuroglancer/datasource/boss/credentials_provider.ts
src/neuroglancer/datasource/boss/frontend.ts
src/neuroglancer/ui/state_editor.ts

This subsumes PR #380.
We have taken the core functionality changes and committed them below in three commits:
* State export and download
* Add credentials management to the python module for BossDB datasources
* Add public access for open data stored in BossDB
> cc: @hannahgooden @BrockWester

Merge in changes from JHU/APL BossDB (rebased)

---

python/neuroglancer/local_volume.py
python/tests/local_volume_test.py

Adds support for TensorStore data sources in `LocalVolume`.

feat(python): support TensorStore data sources in LocalVolume

---

src/neuroglancer/datasource/graphene/frontend.ts
src/neuroglancer/datasource/graphene/graphene.css

code formatting
removed duplicate/extraneous error messages
new buttons and shortcut for graphene tools
this may need to be rebased after the starred_segments pr is merged

fix(datasource/graphene): few small fixes+features for graphene tools

---

src/neuroglancer/util/lerp.ts
src/neuroglancer/widget/invlerp.ts

As I was trying to understand some of the code, I added some comments to help myself. I thought they might be more widely useful, so put them in a PR.
Are PRs like this welcome? No worries if not, but if so I might have more like this as I try and learn enough about the codebase to tackle.https://github.com/google/neuroglancer/issues/482.

Add some comments to lerp and invlerp

---

MANIFEST.in
build_tools/cli.ts
firebase.json
python/build_tools/cibuildwheel.sh
setup.py

Fixes https://github.com/google/neuroglancer/issues/542.

chore: fix missing client bundle in Python wheels

---

python/neuroglancer/coordinate_space.py

I was trying to understand what each of these attributes were, so thought it would be helpful to add docs. I'm not sure if this is the right format for docstrings, happy to re-work if not.

Document attributes on some coordinate space classes

---

src/widget/transfer_function.ts

Parity with the invlerp widget in the transfer function widget. Modified transfer function widget to support the same window zooming or expanding on mouse wheel as invlerp widgets.

feat(transfer-function): add zoom via wheel as in the invlerp widget to the transfer function widget

---

src/segmentation_display_state/property_map.spec.ts
src/segmentation_display_state/property_map.ts

Fixes https://github.com/google/neuroglancer/issues/631.

fix(segment properties): fix negative constraints on numeric properties

---

python/tests/n5_test.py
python/tests/precomputed_test.py
src/sliceview/png/index.ts

Fixes https://github.com/google/tensorstore/issues/209.

fix(png): fix multi-channel png decoding

---

src/credentials_provider/interactive_credentials_provider.ts
src/kvstore/middleauth/credentials_provider.ts
src/layer/layer_data_source.ts
src/util/memoize.spec.ts
src/util/memoize.ts

Fixes https://github.com/google/neuroglancer/issues/715.
Thanks to @chrisj for debugging this issue.

fix(asyncMemoize): fix abort handling

---

src/ui/tool_palette.css

Fixes https://github.com/google/neuroglancer/issues/714.

fix(tool_palette): fix dragging instability due to layer headers

---

docs/json_schema/viewer_state.yml
python/neuroglancer/viewer_state.py
src/data_panel_layout.ts
src/layer_group_viewer.ts
src/viewer.ts

Fixes https://github.com/google/neuroglancer/issues/665.

feat(data_panel_layout): add 4panel-alt layout

---

src/datasource/graphene/backend.ts
src/datasource/graphene/base.ts
src/datasource/graphene/frontend.ts
src/datasource/state_share.ts

Fixes https://github.com/google/neuroglancer/pull/727.

fix(graphene): fix breakage due to kvstore url encoding fixes

---

python/neuroglancer/json_wrappers.py
python/tests/json_wrappers_test.py

Fixes https://github.com/google/neuroglancer/issues/756.

fix(python): Add missing Map.pop method

---

src/sliceview/base.ts

Previously, if a given cross-section view selected a cross section slightly below the lower bound, or (almost) exactly at the upper bound of a volume, all chunks could be considered out of bounds. Instead, the positions should be set such that the cross-section is at the center of a voxel, rather than right at the boundary, and the "position snapping" logic in Neuroglancer tries to ensure that.
However, there are various cases under which such cross-sections may be accidentally requested:
- User specifies an explicit position in the state at integer coordinates for a dimension where voxel centers are at half-integers.
- Due to floating point imprecision, a position exactly at the lower bound ends up slightly below the lower bound.
- Due to the OME-Zarr voxel center confusion bug in …

fix(sliceview): display data when viewport is right on boundary

---

src/display_context.ts

This addreses two bugs in the calculation of clip bounds for rendered panels:
- Previously, rendered panels were clipped to the bounding rects of all ancestors without taking into account `overflow-x` and `overflow-y`.  With this change, `overflow-x` and `overflow-y` are correctly taken into account.
- IntersectionObserver can fail to register changes in bounds due to scrolling. With this commit, scroll events directly trigger recalculation of bounds.
Fixes https://github.com/google/neuroglancer/issues/777

fix(display_context): Fix rendered panel clip bounds

---

docs/conf.py
docs/python/api/index.rst
python/examples/example_read_precomputed_annotations.py
python/neuroglancer/read_precomputed_annotations.py
python/neuroglancer/write_annotations.py

See https://github.com/google/tensorstore/issues/236.

feat(python): add precomputed annotation reader interface

---

src/annotation/index.ts

If you passed an annotation with enum labels and values in the state previously, it would get parsed out of the state and show in the UI -- but the values wouldn't remain in the state. For example:
```
{
"type": "annotation",
"source": {
"url": "local://annotations",
"transform": {
"outputDimensions": {
"x": [
8e-9,
"m"
],
"y": [
8e-9,
"m"
],
"z": [
8e-9,
"m"
]
}
}
},
"tool": "annotatePoint",
"tab": "annotations",
"annotations": [
{
"point": [
25086.916015625,
21193.849609375,
18610
],
"type": "point",
"id": "9209a9dc9c16bbd6181deafa3d384fed3154ab41",
"props": [
"#000000",
0
]
},
{
"point": [
22971.654296875,
17071.798828125,
18610
],
"type": "point",
"id": "f911129824bff974a4edd74f986098385d36f237",
"props": [
"#000000",
0
]
}
],
"annotationProperties": [
{
"id": "color",
"type": "rgb" …
```

Fix: annotation enum values and labels set in JSON state stay in the state

---

src/datasource/render/frontend.ts

feat: Fix validation to skip unrelated stacks with missing metadata for Render datasource

---

src/datasource/zarr/frontend.ts

Fixes https://github.com/google/neuroglancer/issues/832

fix(datasource/zarr): Fix cross-version metadata caching issue
